name: Lint

on: [pull_request]

jobs:
  lint:
    name: Check the code style
    runs-on: ubuntu-20.04

    steps:
      - name: Repository installation
        uses: actions/checkout@v2

      - name: Dependencies installation
        run: make install

      - name: Library building
        run: make build
